export enum EchoAspect {
  TAILLE_ECHOSTRUCURE_NORMALE = 'TAILLE_ECHOSTRUCURE_NORMALE',

  TAILLE_AUGMENTEE = 'TAILLE_AUGMENTEE',

  DIFFICILE_VISUALISER = 'DIFFICILE_VISUALISER',

  ANORMALITE = 'ANORMALITE',
}
